name: Docker Image CI (all)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
        with:
           image: tonistiigi/binfmt:latest
           platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
           platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6,arm/v7,arm/v6,windows-amd64
      -
        name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: zyao97323/cirnobot:master
          platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6,arm/v7,arm/v6,windows-amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # upload build test reports
